#!/bin/sh

if [ $# -eq 0 ]; then
  echo "Input file not specified"

else
  tmp_dir=$(mktemp -d -t pdfi-XXXXXXXXXXXX)
  echo "Using dir $tmp_dir"
  cp "$1" "$tmp_dir"
  f="$(basename -- $1)"
  cwd=$(pwd)
  cd $tmp_dir
  echo "Splitting doc into images..."
  pdftoppm -png "$f" document
  echo "Inverting colors..."
  ${cwd}/magick mogrify -negate *.png
  rm "$f"
  echo "Joining files back together..."
  ${cwd}/magick convert *.png output.pdf
  echo "Cleaning up..."
  rm *.png
  cd $cwd
  echo "Replacing original file..."
  cp "$tmp_dir/output.pdf" "$1"
  echo "Cleaning up..."
  rm -rf "$tmp_dir"
  echo "Done!"
fi
